language: php
php:
  - 5.6
  - 7.0

branches:
    only:
      - master

before_script:
  - phpenv config-rm xdebug.ini
  - composer install -o
  - composer require --dev phpunit/phpunit ^5
  - phpunit --version

script:
  - ./vendor/bin/phpunit -v -c phpunit.xml
